apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-crud-ingress
  labels:
    app: flask-crud
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Adicione outras anotações conforme necessário para seu Ingress Controller
    kubernetes.io/ingress.class: "nginx"  # Descomente se necessário
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Para HTTPS com cert-manager
spec:
  ingressClassName: nginx  # Ajuste conforme seu Ingress Controller
  rules:
  - host: echo.example.com # Altere para seu domínio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-crud-service
            port:
              number: 80
  # Descomente para habilitar HTTPS
  # tls:
  # - hosts:
  #   - flask-crud.local
  #   secretName: flask-crud-tls
